app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('player', 'PlayerController');
Route::resource('team', 'TeamController');
Route::resource('match', 'MatchController');

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Player;

class Team extends Model
{
    protected $table = 'teams';
    protected $fillable = ['player_one', 'player_two', 'team_name'];
    
    public function getName() {
        return $this->name;
    }
    
    public function playerOne() {
        return $this->hasOne('App\Player', 'id', 'player_one');
    }
    
    public function playerTwo() {
        return $this->hasOne('App\Player', 'id', 'player_two');
    }
    
    public function getPlayerOne() {
        
        return Player::find($this->player_one);
    }
    
    public function getPlayerTwo() {
        return Player::find($this->player_two);
//        return isset($this->player_two) ? $this->player_two : '[ No Teammate ]';
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Team;
use App\Player;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Input;
use Validator;
use Redirect;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $teams = Team::all();
        return view('team.index', compact('teams'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $players = ['' => 'Select One'] + Player::lists('name', 'id')->toArray();
        return view('team.create', compact('players'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        
        $validator = Validator::make(
            [
                'player_one' => Input::get('player_one'),
                'player_two' => Input::get('player_two'),
                'team_name' => Input::get('team_name')
            ],
            [
                'player_one' => 'required',
                'team_name' => 'required|unique:teams'
            ]
        );
        
        if($validator->fails()) {
            var_dump(Input::all());
            dd($validator->errors()->all());
            return redirect()->back()->withErrors($validator->errors()->all());
        }
        
        if(Input::get('player_two') == '') {
            $newTeam = Team::create([
                'player_one' => Input::get('player_one'),
                
                'player_two' => null,
                'team_name' => Input::get('team_name')
            ]);
        } else {
            $newTeam = Team::create([
                'player_one' => Input::get('player_one'),
                'player_two' => Input::get('player_two'),
                'team_name' => Input::get('team_name')
            ]);
        }
        return Redirect::route('team.index')->with('message', $newTeam->team_name.' has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $edit = false;
        $team = Team::find($id);
        return view('team.show', compact('team', 'edit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $edit = true;
        $team = Team::find($id);
        $players = ['' => 'Select One'] + Player::lists('name', 'id')->toArray();
        return view('team.show', compact('team', 'edit', 'players'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request)
    {
        $input = array_except(Input::all(), '_method');
        $team = Team::find(Input::get('id'));
        $team->update($input);
        return Redirect::route('team.index')->with('message', $team->team_name.' has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/team/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                
                {!! Form::open(['action' => 'TeamController@store']) !!}
                    {!! Form::label('player_one', 'Player One') !!}
                    {!! Form::select('player_one', $players) !!}
                    {!! Form::label('player_two', 'Player Two') !!}
                    {!! Form::select('player_two', $players) !!}
                    {!! Form::label('team_name', 'Team Name') !!}
                    {!! Form::text('team_name') !!}
                    {!! Form::submit('Create Team') !!}
                {!! Form::close() !!}
            </div>
        </div>
    </body>
</html>

resources/views/team/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
        
        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <navigation class="nav">
            <ul>
                <li>{!! link_to_route('player.index', 'Players') !!}</li>
                <li>{!! link_to_route('team.index', 'Teams') !!}</li>
            </ul>
        </navigation>
        <div class="container">
            <div class="content">
                @if(Session::has('message'))
                    {{ Session::get('message') }}
                @endif
                @foreach($teams as $team)
                <h2>{!! link_to_route('team.show', 'See '.$team->team_name, $team->id) !!}</h2> 
                <p>[ {!! link_to_route('player.show', 'See '.$team->playerOne->name, $team->player_one) !!}
                    @if(isset($team->player_two))
                    , {!! link_to_route('player.show', 'See '.$team->playerTwo->name, $team->player_two) !!}
                    @endif]</p>
                @endforeach
                {!! link_to_route('team.create', 'Create A New Team') !!}
            </div>
        </div>
    </body>
</html>

resources/views/team/show.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                @if(Session::has('message'))
                    {{ Session::get('message') }}
                @endif
                @if(isset($errors))
                    {{ $team->getName() }}
                @endif
                @if($edit == true)
                
                {!! Form::model($team, ['action' => 'TeamController@update', 'method' => 'PATCH']) !!}
                    {!! Form::hidden('id') !!}
                    {!! Form::label('player_one', 'Player One') !!}
                    {!! Form::select('player_one', $players) !!}
                    {!! Form::label('player_two', 'Player Two') !!}
                    {!! Form::select('player_two', $players) !!}
                    {!! Form::label('team_name', 'Team Name') !!}
                    {!! Form::text('team_name') !!}
                    {!! Form::submit('Save Team') !!}
                {!! Form::close() !!}
                
                @else
                <table>
                    <tr>
                        <td>{{ $team->id }}</td>
                        <td>{{ $team->playerOne->name }}</td>
                        <td>{{ $team->playerTwo->name }}</td>
                        <td>{{ $team->team_name }}</td>
                        <td>{{ $team->created_at }}</td>
                        <td>{{ $team->updated_at }}</td>
                    </tr>
                </table>
                {!! link_to_route('team.edit', 'Edit Team', $team->id ) !!}
                
                @endif
                {!! link_to_route('team.index', 'Show All Teams') !!}
                
            </div>
        </div>
    </body>
</html>