app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('player', 'PlayerController');
Route::resource('team', 'TeamController');
Route::resource('match', 'MatchController');

app/Match.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Player;
use Team;

class Match extends Model
{
    protected $table = 'matches';
    protected $fillable = ['team_one', 'team_two', 'team_one_score', 'team_two_score', 'winner', 'loser', 'forfeit', 'disqualified', 'tie', 'bye'];
    
    public function teamOne() {
        return $this->hasOne('App\Team', 'id', 'team_one');
    }
    
    public function teamTwo() {
        return $this->hasOne('App\Team', 'id', 'team_two');
    }
}

app/Http/Controllers/MatchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Team;
use App\Player;
use App\Match;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Input;
use Validator;
use Redirect;

class MatchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $matches = Match::all();
        return view('match.index', compact('matches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $teams = ['' => 'Select One'] + Team::lists('team_name', 'id')->toArray();
        return view('match.create', compact('teams'));
    }
    
    

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            [
                'team_one' => Input::get('team_one'),
                'team_two' => Input::get('team_two')
            ],
            [
                'team_one' => 'required',
                'team_two' => 'required'
            ]
        );
        if($validator->fails()) {
            var_dump(Input::all());
            dd($validator->errors()->all());
            return redirect()->back()->withErrors($validator->errors()->all());
        }
        /* 
         * This defaults to 9 so we can get past foreign key issues. 9 is the 
         * team id that is used for no other team.  Their stats will be for the 
         * garbage 
         */
        $match = Match::create([
            'team_one' => Input::get('team_one'),
            'team_two' => Input::get('team_two'),
            'winner' => 9,
            'loser' => 9,
            'forfeit' => 9,
            'disqualified' => 9
        ]);
        return Redirect::route('match.index')->with('message', 'Your match has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $edit = false;
        $match = Match::find($id);
        return view('match.show', compact('match', 'edit'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $edit = true;
        $match = Match::find($id);
        return view('match.show', compact('match', 'edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/match/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                
                {!! Form::open(['action' => 'MatchController@store']) !!}
                    {!! Form::label('team_one', 'Team One') !!}
                    {!! Form::select('team_one', $teams) !!}
                    {!! Form::label('team_two', 'Team Two') !!}
                    {!! Form::select('team_two', $teams) !!}
                    {!! Form::submit('Create Match') !!}
                {!! Form::close() !!}
            </div>
        </div>
    </body>
</html>

resources/views/match/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
        
        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <navigation class="nav">
            <ul>
                <li>{!! link_to_route('player.index', 'Players') !!}</li>
                <li>{!! link_to_route('team.index', 'Teams') !!}</li>
                <li>{!! link_to_route('match.index', 'Matches') !!}</li>
            </ul>
        </navigation>
        <div class="container">
            <div class="content">
                @if(Session::has('message'))
                    {{ Session::get('message') }}
                @endif
                @foreach($matches as $match)
                <h2>{!! link_to_route('match.show', 'See '.$match->teamOne->team_name.' vs '.$match->teamTwo->team_name, $match->id) !!}</h2> 
                
                @endforeach
                {!! link_to_route('match.create', 'Create A New Match') !!}
            </div>
        </div>
    </body>
</html>

resources/views/match/show.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                @if(Session::has('message'))
                    {{ Session::get('message') }}
                @endif
                @if(isset($errors) && isset($errors->bags))
                    ERRORS :: THEY ARE THERE
                @endif
                
                
                @if($edit == true)
                
                
                
                {!! Form::model($match, ['action' => 'MatchController@update', 'method' => 'PATCH']) !!}
                    {!! Form::hidden('id') !!}
                    {!! Form::label('team_one', 'Team One') !!}
                    {{ Team::find($match->team_one)->team_name }}
                    {!! Form::label('team_two', 'Team Two') !!}
                    {{ Team::find($match->team_two)->team_name }}
                    {!! Form::label('team_one_score', 'Team One Score') !!}
                    {!! Form::text('team_one_score') !!}
                    {!! Form::label('team_two_score', 'Team Two Score') !!}
                    {!! Form::text('team_two_score') !!}
                    
                    {!! Form::label('winner', 'Winner') !!}
                    {!! Form::select('winner', $teams) !!}
                    
                    {!! Form::label('loser', 'Loser') !!}
                    {!! Form::select('loser', $teams) !!}
                    
                    {!! Form::label('forfeit', 'Forfeit') !!}
                    {!! Form::select('forfeit', $teams) !!}
                    
                    {!! Form::label('disqualified', 'Disqualified') !!}
                    {!! Form::select('disqualified', $teams) !!}
                    
                    {!! Form::label('tie', 'Tie') !!}
                    {!! Form::checkbox('tie') !!}
                    
                    {!! Form::label('bye', 'Bye') !!}
                    {!! Form::checkbox('Bye') !!}
                    
                    {!! Form::submit('Save Match') !!}
                {!! Form::close() !!}
                
                @else
                <table>
                    <tr>
                        <td>{{ $match->id }}</td>
                        <td>{{ $match->teamOne->name }}</td>
                        <td>{{ $match->teamTwo->name }}</td>
                        <td>{{ $match->team_one_score }}</td>
                        <td>{{ $match->team_two_score }}</td>
                        <td>{{ $match->winner }}</td>
                        <td>{{ $match->loser }}</td>
                        <td>{{ $match->forfeit }}</td>
                        <td>{{ $match->disqualified }}</td>
                        <td>{{ $match->tie }}</td>
                        <td>{{ $match->bye }}</td>
                        <td>{{ $match->point_difference }}</td>
                        <td>{{ $match->created_at }}</td>
                        <td>{{ $match->updated_at }}</td>
                    </tr>
                </table>
                {!! link_to_route('team.edit', 'Edit Team', $team->id ) !!}
                
                @endif
                {!! link_to_route('team.index', 'Show All Teams') !!}
                
            </div>
        </div>
    </body>
</html>