app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('player', 'PlayerController');
Route::resource('team', 'TeamController');
Route::resource('match', 'MatchController');

app/Player.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    protected $table = 'players';
    protected $fillable = ['name', 'nickname'];
    
    public function getName() {
        return $this->name;
    }
    
    public function getNickName() {
        return $this->nickname;
    }
    
}

app/Http/Controllers/PlayerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Player;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Input;
use Validator;
use Redirect;

class PlayerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $players = Player::all();
        return view('player.index', compact('players'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('player.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            [
                'name' => Input::get('name'),
                'nickname' => Input::get('nickname')
            ],
            [
                'name' => 'required',
                'nickname' => 'required|unique:players'
            ]
        );
        
        if($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors()->all());
        }
        
        $newPlayer = Player::create([
            'name' => Input::get('name'),
            'nickname' => Input::get('nickname')
        ]);
        return Redirect::route('player.index')->with('message', $newPlayer->name.' has been created');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $edit = false;
        $player = Player::find($id);
        return view('player.show', compact('player', 'edit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $player = Player::find($id);
        $edit = true;
        return view('player.show', compact('player', 'edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request)
    {
        $input = array_except(Input::all(), '_method');
        
        $player = Player::find(Input::get('id'));
        $player->update($input);
        return Redirect::route('player.index')->with('message', $player->name.' has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        
    }
}

resources/views/player/create.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                
                {!! Form::open(['action' => 'PlayerController@store']) !!}
                    {!! Form::label('name', 'Name') !!}
                    {!! Form::text('name') !!}
                    {!! Form::label('nickname', 'Nickname') !!}
                    {!! Form::text('nickname') !!}
                    {!! Form::submit('Create Player') !!}
                {!! Form::close() !!}
            </div>
        </div>
    </body>
</html>

resources/views/player/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
        
        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <navigation class="nav">
            <ul>
                <li>{!! link_to_route('player.index', 'Players') !!}</li>
                <li>{!! link_to_route('team.index', 'Teams') !!}</li>
                <!--<li> link_to_route('match.index', 'Matches') !!}</li>-->
            </ul>
        </navigation>
        <div class="container">
            <div class="content">
                @if(Session::has('message'))
                    {{ Session::get('message') }}
                @endif
                @foreach($players as $player)
                <p style="font-size: 2em;">{{ $player->name }} [ <a href="{{ route('player.show', $player->id) }}">{{ $player->nickname }}</a> ]</p>
                <p><a href="{{ route('player.edit', [$player->id]) }}">Edit {{ $player->name }}</a>
                @endforeach
                <p> {!! link_to_route('player.create', 'Create A New Player') !!}
            </div>
        </div>
    </body>
</html>

resources/views/player/show.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                @if(Session::has('message'))
                    {{ Session::get('message') }}
                @endif
                @if(isset($errors))
                    {{ $player->getNickName() }}
                @endif
                @if($edit == true)
                
                {!! Form::model($player, ['action' => 'PlayerController@update', 'method' => 'PATCH']) !!}
                    {!! Form::hidden('id') !!}
                    {!! Form::label('name', 'Name') !!}
                    {!! Form::text('name') !!}
                    {!! Form::label('nickname', 'Nickname') !!}
                    {!! Form::text('nickname') !!}
                    {!! Form::submit('Save Player') !!}
                {!! Form::close() !!}
                
                @else
                <table>
                    <tr>
                        <td>{{ $player->id }}</td>
                        <td>{{ $player->name }}</td>
                        <td>{{ $player->nickname }}</td>
                        <td>{{ $player->image }}</td>
                        <td>{{ $player->created_at }}</td>
                        <td>{{ $player->updated_at }}</td>
                    </tr>
                </table>
                {!! link_to_route('player.edit', 'Edit Player', $player->id ) !!}
                
                @endif
                {!! link_to_route('player.index', 'Show All Players') !!}
                
            </div>
        </div>
    </body>
</html>